name: Docker Compose Test

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test--<service>:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Compose: Prepare"
        run: |
          cd '<service>'
      -
        name: "Compose: Start"
        run: |
          docker-compose up -d
      -
        name: "Compose: Wait"
        run: |
          sleep <SECONDS>s
      -
        name: "Compose: Test"
        run: |
          docker-compose exec -T <SERVICE> <COMMAND> <ARG>...
