name: Docker Compose Test

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test--pihole_cloudflared:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Docker: Compose prepare"
        run: |
          cd '<project>'
      -
        name: "Docker: Compose start"
        run: |
          docker-compose up -d
          sleep 5s
      -
        name: "Docker: Compose test"
        run: |
          docker-compose exec -T <service> <cmd> <arg>...
